services:
  secure-authentication-be:
    image: secure-authentication-be:latest
    container_name: secure-authentication-be
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      AUTHENTICATION_SERVER_ENV: ${AUTHENTICATION_SERVER_ENV}
    restart: unless-stopped
    networks:
      - secure-authentication-be_authentication-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  secure-authentication-be_authentication-network:
    external: true
